### ISSUE TITLE
Appreciation for windows 95 VM

### ISSUE THREAD

**Issue by oalotfy** [anonymousaga/UTM#1]
Bro i had SUCH A HARD TIME GETTING WINDOWS 95 TO WORK ON UTM AND YOURS IS THE ONLY ONE THAT PROPERLY WORKS FOR ME THANK YOU SO MUCH ABHIJEET GHOSH I LOVE YOU

p.s how did you get it to work pls tell me ok thanks

**Comment by anonymousaga** [comment]
Hello, thanks for the feedback! Ill send you the details of how i got it in a bit. Just wondering, do you know me? Or otherwise, how did you know my name? Thanks. Glad i could help you. 🙂

i have other VMs such as windows 1.0, 2.0, 3.0, 3.1.1, nt 4.0, 2000, me, xp, vista, 7, 8, and 11 arm. As well as some old macos 9.2, 10.1, 10.3, 10.5

**Comment by anonymousaga** [comment]
Also, I would like to mention I posted a new windows 95 VM yesterday fixing some protection bugs i got and some drivers. I'm not sure if you are using that one.

**Comment by aashrithm29** [comment]
Yeah, do you know Abhijeet @oalotfy. Pretty cool. He helped me with Ubuntu lol

**Comment by oalotfy** [comment]
Haha, I don’t actually know you personally lol but the name was registered on the windows 95 VM so I assumed that was you 😆
I think I’m using the newest version because I just downloaded it less than a day ago, thanks for the response!
p.s do you guys mind sharing your discords? I’d like to discuss with you guys UTM things if you don’t mind.

**Comment by anonymousaga** [comment]
Oh! Here is my discord: ∫ sin(x) dx = -cos(x) + C#1100

**Comment by aashrithm29** [comment]
@oalotfy my discord is @aashrithm29#3355
(Yes, very creative username lolol)
